export const USER_LOGGIN = 'USER_LOGGIN'
export const USER_LOGOUT = 'USER_LOGOUT'
export const USER_LOGGED = 'USER_LOGGED'

export const GET_MOVIES = 'GET_MOVIES'
export const MOVIES_RECEIVED = 'MOVIES_RECEIVED'