export const USER_LOGGIN = 'USER_LOGGIN'
export const USER_LOGOUT = 'USER_LOGOUT'
export const USER_LOGGED = 'USER_LOGGED'
export const USER_REGISTRATION = 'USER_REGISTRATION'
export const USER_SHOW_LOGIN_PROPOSE = 'USER_SHOW_LOGIN_PROPOSE'
export const USER_REMOVE_LOGIN_PROPOSE = 'USER_REMOVE_LOGIN_PROPOSE'

export const GET_MOVIES = 'GET_MOVIES'
export const MOVIES_RECEIVED = 'MOVIES_RECEIVED'

export const GET_MOVIE = 'GET_MOVIE'
export const MOVIE_RECEIVED = 'MOVIE_RECEIVED'

export const ERROR_RECEIVED = 'ERROR_RECEIVED'
export const ERROR_RESET = 'ERROR_RESET'